services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: laravel-app
    volumes:
      - .:/var/www/html
    depends_on:
      - postgres
      - redis
    environment:
      APP_ENV: production
    networks:
      - laravel

  nginx:
    image: nginx:alpine
    container_name: laravel-nginx
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

  postgres:
    image: postgres:15
    container_name: laravel-postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: apdiamantes
      POSTGRES_USER: tonho
      POSTGRES_PASSWORD: 2305
    networks:
      - laravel


  redis:
    image: redis:alpine
    container_name: laravel-redis
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    networks:
      - laravel

volumes:
  pgdata:
  redisdata:

networks:
  laravel:
    driver: bridge
