services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: laravel-app
    volumes:
      - .:/var/www/html
      - ./docker/php/php-dev.ini:/usr/local/etc/php/conf.d/99-custom.ini
      - ./docker/bash_history/.bash_history:/root/.bash_history
    depends_on:
      - postgres
      - redis
    environment:
      APP_ENV: local
    networks:
      - laravel

  nginx:
    image: nginx:alpine
    container_name: laravel-nginx
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

  postgres:
    image: postgres:15
    container_name: laravel-postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker/postgres/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./docker/postgres/pg_hba.conf:/etc/postgresql/pg_hba.conf
    environment:
      POSTGRES_DB: apdiamantes
      POSTGRES_USER: tonho
      POSTGRES_PASSWORD: 2305
    command: >
      postgres
      -c 'config_file=/etc/postgresql/postgresql.conf'
      -c 'hba_file=/etc/postgresql/pg_hba.conf'

    networks:
      - laravel


  redis:
    image: redis:alpine
    container_name: laravel-redis
    #ports:
    #  - "6379:6379"
    volumes:
      - redisdata:/data
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    networks:
      - laravel


volumes:
  pgdata:
  redisdata:

networks:
  laravel:
    driver: bridge
